<?php

namespace ScrumBoardItBundle\Repository;

/**
 * DatabaseUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatabaseUserRepository extends \Doctrine\ORM\EntityRepository
{
}
