<?php

namespace ScrumBoardItBundle\Repository;

/**
 * SbiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SbiUserRepository extends \Doctrine\ORM\EntityRepository
{
}
